name: Release Addon

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: 'Build Local Addon'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Addon
        run: |
          TAR_FILE=$(npm pack --json | jq -r '.[0].filename')
          echo "TAR_FILE=$TAR_FILE" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: ${{ env.TAR_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
